### ISSUE TITLE
Hangs Firefox

### ISSUE THREAD

**Issue by hornage** [lesjames/history-api-demo#2]
Great bit of code, thanks for sharing. One question, I've tried editing to work in Firefox but no joy, Firefox constantly hangs after about 5 clicks :( any ideas?

**Comment by lesjames** [comment]
I wrote the demo for Chrome. What's happening in Firefox is the old content isn't being removed after transition. Notice I only included the transition event listener for webkit.

``` javascript
// when finished animating remove old wrapper
.one('webkitTransitionEnd', function () {
    $(this).remove();
});
```

**Comment by hornage** [comment]
No worries, I was being dumb there! :''( Thanks for the code! :+1:

**Comment by lesjames** [comment]
Added note to readme about this demo only working in Webkit.
