### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by urre** [lesjames/history-api-demo#3]
What's your prefered way of tracking pageviews using Google Analytics in this demo?

**Comment by lesjames** [comment]
You should be able to push pageviews to GA with something like

```
_gaq.push(['_trackPageview', '/somepage']);
```

**Comment by urre** [comment]
Yep, I used this right after history.pushstate():

// Get relative link from the clicked link
var relativeurl = $(this).attr('href');

// Track pageview using GA (Universal Analytics)
ga('send', 'pageview', relativeurl);

also need to add it when using back/forward buttons

Maybe something to add to the demo?

**Comment by lesjames** [comment]
I'm not going to update the demo, but if you would like to incorporate a GA tracking example submit a pull request and I'll merge it in.

**Comment by urre** [comment]
Ok
